schema:
  - "http://localhost:5001/graphql"
documents:
  - "./src/graphql/**/*.graphql"
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo